/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FormItemModel } from "./model/form.model";
export { FormItemModel } from "./model/form.model";
export namespace Components {
    interface AmountInputComponent {
        /**
          * @prop {FormItemModel} model - The form item model containing value and validators.
         */
        "model": FormItemModel;
    }
    interface AppComponent {
    }
    interface FormComponent {
    }
}
export interface AmountInputComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAmountInputComponentElement;
}
declare global {
    interface HTMLAmountInputComponentElement extends Components.AmountInputComponent, HTMLStencilElement {
    }
    var HTMLAmountInputComponentElement: {
        prototype: HTMLAmountInputComponentElement;
        new (): HTMLAmountInputComponentElement;
    };
    interface HTMLAppComponentElement extends Components.AppComponent, HTMLStencilElement {
    }
    var HTMLAppComponentElement: {
        prototype: HTMLAppComponentElement;
        new (): HTMLAppComponentElement;
    };
    interface HTMLFormComponentElement extends Components.FormComponent, HTMLStencilElement {
    }
    var HTMLFormComponentElement: {
        prototype: HTMLFormComponentElement;
        new (): HTMLFormComponentElement;
    };
    interface HTMLElementTagNameMap {
        "amount-input-component": HTMLAmountInputComponentElement;
        "app-component": HTMLAppComponentElement;
        "form-component": HTMLFormComponentElement;
    }
}
declare namespace LocalJSX {
    interface AmountInputComponent {
        /**
          * @prop {FormItemModel} model - The form item model containing value and validators.
         */
        "model"?: FormItemModel;
        /**
          * Emitted when the form item model is updated.
          * @event update
         */
        "onUpdate"?: (event: AmountInputComponentCustomEvent<FormItemModel>) => void;
    }
    interface AppComponent {
    }
    interface FormComponent {
    }
    interface IntrinsicElements {
        "amount-input-component": AmountInputComponent;
        "app-component": AppComponent;
        "form-component": FormComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "amount-input-component": LocalJSX.AmountInputComponent & JSXBase.HTMLAttributes<HTMLAmountInputComponentElement>;
            "app-component": LocalJSX.AppComponent & JSXBase.HTMLAttributes<HTMLAppComponentElement>;
            "form-component": LocalJSX.FormComponent & JSXBase.HTMLAttributes<HTMLFormComponentElement>;
        }
    }
}
